name: NPM Publish Alpha

on:
  push:
    branches-ignore:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - name: Bump version (alpha)
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [ "$BRANCH_NAME" != "main" ]; then
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            ALPHA_VERSION="${CURRENT_VERSION}-alpha.$(date +%s)"
            npm version --no-git-tag-version $ALPHA_VERSION
            echo "Alpha version: $ALPHA_VERSION"
          fi

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc

      - name: Publish to NPM
        run: npm publish --tag alpha
